import { 
  APP_ENV_APIKEY,
  APP_ENV_AUTHDOMAIN,
  APP_ENV_DATABASEURL,
  APP_ENV_PROJECTID,
  APP_ENV_STORAGEBUCKET,
  APP_ENV_MESSAGINGSENDERID,
  APP_ENV_APPID,
  APP_ENV_CREDENTIALADMIN
} from '@env'

export default {
  APP_ENV_APIKEY,
  APP_ENV_AUTHDOMAIN,
  APP_ENV_DATABASEURL,
  APP_ENV_PROJECTID,
  APP_ENV_STORAGEBUCKET,
  APP_ENV_MESSAGINGSENDERID,
  APP_ENV_APPID,
  APP_ENV_CREDENTIALADMIN
}